Repository kowoohyuk/baseball, pull requests merged in 2021-05, with the labels that each got.

#7 [#2] 컴포넌트 설계
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/src/App.css
  fe/src/App.js
  fe/src/components/game-list/GameList.jsx
  fe/src/components/game-list/GameListItem.jsx
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/board/Board.jsx
  fe/src/components/game-play/log/Log.jsx
  fe/src/components/game-play/player/Player.jsx
  fe/src/components/game-play/score/Score.jsx
  fe/src/components/game-roster/GameRoster.jsx
  fe/src/components/game-score/GameScore.jsx
  fe/src/components/ui/PopUp.jsx
  fe/src/images/background.png
  fe/src/index.css
  fe/src/index.js
Labels: documentation, feat, front

#9 [FE] 인트로 게임리스트 UI 구현
  fe/src/App.js
  fe/src/components/game-list/GameList.jsx
  fe/src/components/game-list/GameListItem.jsx
Labels: feat, front

#10 [BE] 기본 세팅 진행
  .idea/.gitignore
  .idea/baseball.iml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/be.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  be/.gitignore
  be/.gradle/6.7/executionHistory/executionHistory.bin
  be/.gradle/6.7/executionHistory/executionHistory.lock
  be/.gradle/6.7/fileChanges/last-build.bin
  be/.gradle/6.7/fileHashes/fileHashes.bin
  be/.gradle/6.7/fileHashes/fileHashes.lock
  be/.gradle/6.7/gc.properties
  be/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  be/.gradle/buildOutputCleanup/cache.properties
  be/.gradle/buildOutputCleanup/outputFiles.bin
  be/.gradle/checksums/checksums.lock
  be/.gradle/checksums/md5-checksums.bin
  be/.gradle/checksums/sha1-checksums.bin
  be/.gradle/configuration-cache/gc.properties
  be/.gradle/vcs-1/gc.properties
  be/.idea/.gitignore
  be/.idea/be.iml
  be/.idea/misc.xml
  be/.idea/modules.xml
  be/.idea/vcs.xml
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/baseball/BaseballApplication.java
  be/src/main/java/baseball/controller/TeamController.java
  be/src/main/java/baseball/domain/Player.java
  be/src/main/java/baseball/domain/Team.java
  be/src/main/java/baseball/repository/TeamRepository.java
  be/src/main/resources/application.properties
  be/src/main/resources/schema.sql
Labels: back

#11 [#4] feat: :sparkles: 팝업 컴포넌트 구현
  fe/src/components/ui/PopUp.jsx
Labels: feat, front

#12 [#5] feat: :sparkles: 선수 명단 팝업 UI
  fe/src/components/game-list/GameList.jsx
  fe/src/components/game-roster/GameRoster.jsx
  fe/src/components/game-roster/TeamRoster.jsx
  fe/src/components/ui/PopUp.jsx
Labels: feat, front

#13 [FE] 상세 점수 팝업 UI
  fe/src/components/game-score/GameScore.jsx
  fe/src/components/game-score/GameScoreList.jsx
  fe/src/components/ui/PopUp.jsx
Labels: feat, front

#16 [#14] Play 컴포넌트 공통 UI 구현
  fe/src/App.js
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/board/Board.jsx
  fe/src/components/game-play/log/Log.jsx
  fe/src/components/game-play/player/Player.jsx
  fe/src/components/game-play/score/Score.jsx
Labels: front

#19 [#15] chore: :wrench: 임시 data 추가
  fe/src/components/game-play/GamePlay.jsx
Labels: front

#20 [FE] game-play score UI구현
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/score/Score.jsx
Labels: feat, front

#21 [FE] game play player UI 구현
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/player/Player.jsx
Labels: feat, front

#22 [#18] Game-play Log UI 구현
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/log/Log.jsx
  fe/src/components/game-play/player/Player.jsx
  fe/src/index.css
Labels: feat, front

#24 [#23] game board UI 구현
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/board/BallCount.jsx
  fe/src/components/game-play/board/Board.jsx
  fe/src/components/game-play/board/Inning.jsx
  fe/src/components/game-play/board/Screen.jsx
Labels: feat, front

#26 [FE] [#25] 팝업 애니메이션 구현
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/src/App.css
  fe/src/App.js
  fe/src/components/game-list/GameList.jsx
  fe/src/components/game-list/GameListItem.jsx
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/board/BallCount.jsx
  fe/src/components/game-play/board/Board.jsx
  fe/src/components/game-play/board/Inning.jsx
  fe/src/components/game-play/board/Screen.jsx
  fe/src/components/game-play/log/Log.jsx
  fe/src/components/game-play/player/Player.jsx
  fe/src/components/game-play/popup/roster/Roster.jsx
  fe/src/components/game-play/popup/roster/TeamRoster.jsx
  fe/src/components/game-play/popup/score/Score.jsx
  fe/src/components/game-play/popup/score/ScoreList.jsx
  fe/src/components/game-play/score/Score.jsx
  fe/src/components/ui/PopUp.jsx
  fe/src/images/background.png
  fe/src/index.css
  fe/src/index.js
Labels: feat, front

#28 [#25] feat: :sparkles: 팝업 애니메이션 구현
  fe/src/App.js
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/popup/roster/Roster.jsx
  fe/src/components/game-play/popup/roster/TeamRoster.jsx
  fe/src/components/game-play/popup/score/Score.jsx
  fe/src/components/game-play/popup/score/ScoreList.jsx
  fe/src/components/ui/PopUp.jsx
Labels: feat, front

#30 [#29] refactor: :hammer: 리뷰 기반 리팩토링
  fe/src/App.js
  fe/src/components/game-list/GameList.jsx
  fe/src/components/game-list/GameListItem.jsx
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/board/BallCount.jsx
  fe/src/components/game-play/board/Board.jsx
  fe/src/components/game-play/board/Inning.jsx
  fe/src/components/game-play/board/Screen.jsx
  fe/src/components/game-play/log/Log.jsx
  fe/src/components/game-play/player/Player.jsx
  fe/src/components/game-play/popup/roster/Roster.jsx
  fe/src/components/game-play/popup/roster/RosterPlayer.jsx
  fe/src/components/game-play/popup/roster/TeamRoster.jsx
  fe/src/components/game-play/popup/score/Score.jsx
  fe/src/components/game-play/popup/score/ScoreList.jsx
  fe/src/components/game-play/score/Score.jsx
  fe/src/components/ui/PopUp.jsx
  fe/src/index.css
Labels: front, refactor

#32 [#31]feat::sparkles: pitch 클릭 이벤트 구현
  fe/src/components/game-play/board/Board.jsx
  fe/src/components/game-play/board/Screen.jsx
Labels: feat, front

#37 [#33] feat: :sparkles: 라운드 및 턴 구현, 멤버 리스트 일부 구현
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/board/BallCount.jsx
  fe/src/components/game-play/board/Board.jsx
  fe/src/components/game-play/popup/roster/Roster.jsx
  fe/src/components/game-play/popup/roster/RosterPlayer.jsx
  fe/src/components/game-play/popup/roster/TeamRoster.jsx
  fe/src/util/api.js
Labels: feat, front

#41 [#40]feat: pitch 시 주자 애니메이션
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/board/Board.jsx
  fe/src/components/game-play/board/Screen.jsx
  fe/src/components/game-play/score/Score.jsx
  fe/src/hooks/useScoreNBase.js
Labels: feat, front

#43 [FE] 라우터 설정 완료
  fe/package-lock.json
  fe/package.json
  fe/src/App.js
  fe/src/components/game-list/GameList.jsx
  fe/src/components/game-list/GameListItem.jsx
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/board/Screen.jsx
  fe/src/components/game-play/player/Player.jsx
  fe/src/hooks/useFetch.js
Labels: feat, front

#44 [FE] fetch처리 완료
  fe/src/components/game-list/GameList.jsx
  fe/src/components/game-list/GameListItem.jsx
  fe/src/components/game-play/GamePlay.jsx
  fe/src/components/game-play/board/Board.jsx
  fe/src/components/game-play/board/Screen.jsx
  fe/src/components/game-play/log/Log.jsx
  fe/src/components/game-play/player/Player.jsx
  fe/src/components/game-play/popup/roster/Roster.jsx
  fe/src/components/game-play/popup/roster/RosterPlayer.jsx
  fe/src/components/game-play/popup/roster/TeamRoster.jsx
  fe/src/components/game-play/popup/score/Score.jsx
  fe/src/components/game-play/popup/score/ScoreList.jsx
  fe/src/components/game-play/score/Score.jsx
  fe/src/components/ui/PopUp.jsx
  fe/src/hooks/useFetch.js
  fe/src/util/api.js
Labels: feat, front
